muvm-guest: For debug builds, source muvm-hidpipe from current path as well
Same as commit d89ddbe7d022 ("env: For debug builds, source muvm
binaries from current executable path"), but for muvm-hidpipe, which
was imported into muvm by commit 44d33a39eb20 ("hidpipe: merge hidpipe
project into muvm").

Otherwise I get:

  Error: Failed to execute `muvm-hidpipe` as child process

  Caused by:
      No such file or directory (os error 2)

Signed-off-by: Stefano Brivio <sbrivio@redhat.com>